### PR TITLE
Feature: support for 1804 LTS

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
we have another build failing with a vault issue that might be systemic. I don't want to begin replacing this server only to encounter vault issues I can't solve. Giving build a kick and if it's still green I'll continue

**Comment by lsh-0** [comment]
yup, borked. cc @giorgiosironi 

holding off on replacing any ec2 instances until this is stitched up.

**Comment by giorgiosironi** [comment]
See https://github.com/elifesciences/issues/issues/4755 as I tried to roll back the Vault token change but that didn't work.

**Comment by giorgiosironi** [comment]
Green again.

**Comment by lsh-0** [comment]
thanks, @giorgiosironi

**Pull request merged**
